version: '3.8'

services:
  vouchers-db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vouchers
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  vouchers-backend:
    container_name: wecan-vouchers-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://vouchers-db:5432/vouchers
    depends_on:
      - vouchers-db
    ports:
      - "8080:8080"

  vouchers-frontend:
    image: node:18-alpine
    container_name: wecan-vouchers-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    command: ["npm", "start"]

volumes:
  postgres_data: